--ozone-platform-hint=auto
--enable-features=AcceleratedVideoDecodeLinuxGL,VaapiVideoEncoder,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,WebRTCPipeWireCapturer, TouchpadOverscrollHistoryNavigation                                             
--enable-gpu-rasterization
--ignore-gpu-blocklist
--enable-zero-copy
--disable-gpu-memory-buffer-video-frames
