id = "just"
name = "Justfile"
version = "0.1.4"
schema_version = 1
description = "Justfile syntax highlighting"
repository = "https://github.com/jackTabsCode/zed-just"
authors = ["Jack T. <jack@jackt.space>"]
themes = []
icon_themes = []
languages = ["languages/just"]

[lib]

[grammars.just]
repository = "https://github.com/IndianBoy42/tree-sitter-just"
rev = "3f90d24eb8c8d9e8c74fee7120d79c3ec7229f26"

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
