# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule = tile,^(Microsoft-edge)$
windowrule = tile,^(Brave-browser)$
windowrule = tile,^(Chromium)$
windowrule = float,^(pavucontrol)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$
windowrule = float,^(qalculate-gtk)$

# Browser Picture in Picture
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = move 69.5% 4%, title:^(Picture-in-Picture)$

# Application rules
windowrulev2 = workspace 1, class:^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr)$
windowrulev2 = workspace 2, class:^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$
windowrulev2 = workspace 2, class:^([Ee]lement)$
windowrulev2 = workspace 3, class:^([Ff]ilezilla)$
windowrulev2 = workspace 3, class:^([Tt]hunderbird)$
windowrulev2 = workspace 5, class:([Bb]itwarden)$

windowrule=opacity 0.96,vesktop
windowrule=opacity 0.96,discord