id = "catppuccin-icons"
name = "Catppuccin Icons"
version = "1.19.0"
schema_version = 1
description = "🦊 Soothing pastel icons for Zed"
repository = "https://github.com/catppuccin/zed-icons"
authors = ["Catppuccin <releases@catppuccin.com>"]
themes = []
icon_themes = ["icon_themes/catppuccin-icons.json"]
languages = []
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
